package chatbot.demo.models;

public enum PedidoEstado {
    SAUDACAO,
    ESCOLHER_PIZZA,
    ESCOLHER_TAMANHO,
    ESCOLHER_OUTRA_PIZZA,
    ESCOLHER_BEBIDA,
    ESCOLHER_OUTRA_BEBIDA,
    ADICIONAR_OBSERVACAO,
    ADICIONAR_TELEFONE,
    ADICIONAR_NOME,
    ADICIONAR_ENDEREÇO,
    CONFIRMAR_PEDIDO,
    ADICIONAR_METODO_DE_PAGAMENTO,
    ADICIONAR_TROCO,
    PEDIDO_CONFIRMADO;
    
}
